---
name: Release Images

on:
  push:
    branches:
      - master
    tags:
      - 'v**'

jobs:
  e2e:
    name: E2E
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Reclaim free space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile

      - name: Run E2E deployment and tests
        run: make e2e

      - name: Post mortem
        if: failure()
        run: make post-mortem

      - name: Clean up E2E deployment
        run: make cleanup

  release:
    name: Release Images
    needs: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Release the Lighthouse images
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          IMAGES_ARGS: --nocache
          RELEASE_ARGS: lighthouse-agent lighthouse-coredns
        run: |
          if [[ $GITHUB_REF =~ "/tags/" ]]; then
              tags="${GITHUB_REF##*/}"
              { echo $tags | grep -q -v -; } && tags+=" latest"
              RELEASE_ARGS+=" --tag \"$tags\""
          fi
          make images release
